os: linux
language: ruby
services:
  - docker

before_install:
  - docker build -t xpamou1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xpamou1/react-test npm test -- --coverage

after_success:
  - docker build -t xpamou1/complex-client ./client
  - docker build -t xpamou1/complex-nginx ./nginx
  - docker build -t xpamou1/complex-worker ./worker
  - docker build -t xpamou1/complex-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "xpamou1" --password-stdin

  - docker push xpamou1/complex-nginx
  - docker push xpamou1/complex-worker
  - docker push xpamou1/complex-server
  - docker push xpamou1/complex-client
