apiVersion: v1
kind: Pod
metadata:
  name: client-pod # name pod use for loggen 
  labels:
    component: web # use for node config
spec:
  containers:
  - name: client # use for name network
    image: xpamou1/complex-client:latest # name from docker hub
    ports: 
      - containerPort: 3000 # open 3000 port to outside world 